import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
//import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className='text-white'>Admin Homepage</h1>
        <Link href='/admin/newProduct' className="text-white text-xl font-bold hover:underline hover:text-blue-700 active:text-gray-500">Create New Product</Link>
        <Link href='/admin/removeProduct' className="text-white text-xl font-bold hover:underline hover:text-blue-700 active:text-gray-500">Remove Product</Link>
        <Link href='/admin/updateInventory' className="text-white text-xl font-bold hover:underline hover:text-blue-700 active:text-gray-500">Update Inventory</Link>
        <Link href='/admin/emailMailingList' className="text-white text-xl font-bold hover:underline hover:text-blue-700 active:text-gray-500">Email Mailing List</Link>
      </main>
    </>
  );
};

export default Home;